name: .NET Core

on:
  push:
    branches: [ StreamReaderTest ]
  pull_request:
    branches: [ StreamReaderTest ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test-All
      run: dotnet test --no-restore --verbosity normal
    - name: Test-StreamReader
      run: dotnet test --filter ClassName=NSonic.Tests.StreamReaderTests --no-restore --verbosity normal
